version: 0.2
phases:
  install:
    commands:
      - echo "Installing Node.js dependencies..."
      - |
        # Navigate to web directory (handle different source locations)
        if [ -d "web" ]; then
          cd web
        elif [ -d "${CODEBUILD_SRC_DIR}/web" ]; then
          cd "${CODEBUILD_SRC_DIR}/web"
        else
          echo "ERROR: Could not find web directory"
          echo "CODEBUILD_SRC_DIR: ${CODEBUILD_SRC_DIR}"
          ls -la
          exit 1
        fi
        echo "Current directory: $(pwd)"
        echo "Checking for package.json and package-lock.json..."
        ls -la package.json package-lock.json 2>/dev/null || echo "WARNING: package files not found"
        npm ci
  pre_build:
    commands:
      - |
        # Ensure we're in web directory
        if [ -d "web" ]; then
          cd web
        elif [ -d "${CODEBUILD_SRC_DIR}/web" ]; then
          cd "${CODEBUILD_SRC_DIR}/web"
        fi
        echo "Building web application..."
  build:
    commands:
      - |
        # Ensure we're in web directory
        if [ -d "web" ]; then
          cd web
        elif [ -d "${CODEBUILD_SRC_DIR}/web" ]; then
          cd "${CODEBUILD_SRC_DIR}/web"
        fi
        npm run build
      - |
        # Determine S3 bucket name
        S3_BUCKET_NAME="${S3_BUCKET}"
        
        # If not provided, try to fetch from Terraform outputs
        if [ -z "${S3_BUCKET_NAME}" ] || [ "${S3_BUCKET_NAME}" = "" ]; then
          echo "S3_BUCKET not provided, attempting to fetch from Terraform outputs..."
          
          # Navigate to infra directory
          if [ -d "infra" ]; then
            cd infra
          elif [ -d "${CODEBUILD_SRC_DIR}/infra" ]; then
            cd "${CODEBUILD_SRC_DIR}/infra"
          elif [ -d "${CODEBUILD_SRC_DIR_TerraformDeployOutputDev}/infra" ]; then
            cd "${CODEBUILD_SRC_DIR_TerraformDeployOutputDev}/infra"
          fi
          
          # Initialize Terraform to read outputs (if in infra directory)
          if [ -f "main.tf" ]; then
            ENV="${TF_VAR_environment:-dev}"
            terraform init -backend-config="bucket=agentic-retail-os-terraform-state" -backend-config="key=${ENV}/terraform.tfstate" -backend-config="region=us-east-1" -backend-config="encrypt=true" -backend-config="dynamodb_table=agentic-retail-os-terraform-locks" > /dev/null 2>&1 || true
            S3_BUCKET_NAME=$(terraform output -raw web_bucket_id 2>/dev/null || echo "")
            if [ ! -z "${S3_BUCKET_NAME}" ] && [ "${S3_BUCKET_NAME}" != "" ]; then
              echo "Found S3 bucket from Terraform outputs: ${S3_BUCKET_NAME}"
            fi
            cd - > /dev/null 2>&1 || true
          fi
        fi
        
        # Final check
        if [ -z "${S3_BUCKET_NAME}" ] || [ "${S3_BUCKET_NAME}" = "" ]; then
          echo "ERROR: S3_BUCKET environment variable not set and could not fetch from Terraform outputs"
          echo "Please provide S3_BUCKET parameter when deploying the pipeline, or ensure Terraform outputs are available"
          exit 1
        fi
        
        echo "Deploying to S3 bucket: ${S3_BUCKET_NAME}"
        # Ensure we're in web directory for dist/ path
        if [ -d "web" ]; then
          cd web
        elif [ -d "${CODEBUILD_SRC_DIR}/web" ]; then
          cd "${CODEBUILD_SRC_DIR}/web"
        fi
        # dist/ should be in the web directory after npm run build
        if [ -d "dist" ]; then
          aws s3 sync dist/ s3://${S3_BUCKET_NAME}/ --delete
          echo "Deployment complete"
        else
          echo "ERROR: dist/ directory not found. Build may have failed."
          exit 1
        fi
  post_build:
    commands:
      - |
        if [ ! -z "${CloudFrontDistributionId}" ] && [ "${CloudFrontDistributionId}" != "" ]; then
          echo "Creating CloudFront invalidation..."
          aws cloudfront create-invalidation --distribution-id ${CloudFrontDistributionId} --paths "/*"
        else
          echo "CloudFront distribution ID not provided, skipping invalidation"
        fi
artifacts:
  files:
    - '**/*'
  base-directory: dist

